// Certificate System Types
// Generated by Task 1 of certificate-system plan

export interface FieldConfig {
  key: 'student_name' | 'score' | 'quiz_title' | 'date' | 'teacher_name' | 'custom_note';
  x: number;
  y: number;
  fontSize: number;
  fontWeight?: 'normal' | 'bold';
  color?: string;
  align?: 'left' | 'center' | 'right';
  maxWidth?: number;
}

export interface CertificateTemplate {
  id: string;
  school_id: string;
  name: string;
  bg_image_r2_key: string;
  thumbnail_r2_key: string | null;
  fields_config: string; // JSON string của FieldConfig[]
  is_active: number;
  created_at: string;
  created_by: string;
}

export interface CertificateBatch {
  id: string;
  teacher_id: string;
  class_id: string | null;
  quiz_id: string | null;
  template_id: string;
  title: string;
  custom_note: string | null;
  status: 'draft' | 'sending' | 'sent' | 'error';
  sent_at: string | null;
  created_at: string;
}

export interface Certificate {
  id: string;
  batch_id: string;
  student_id: string;
  student_name: string;
  student_score: number | null;
  quiz_title: string | null;
  png_r2_key: string | null;
  render_status: 'pending' | 'done' | 'error';
  error_message: string | null;
  issued_at: string;
  is_revoked: number;
}
